default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: postgres

development:
  <<: *default
  database: alimente_development

test: &test
  <<: *default
  database: alimente_test

production:
  <<: *default
  database: alimente_production
  username: alimente
  password: <%= ENV['WECARE_DATABASE_PASSWORD'] %>
